### ISSUE TITLE
Tapo P100 issue (

### ISSUE THREAD

**Issue by technow0rker** [fishbigger/TapoP100#1]
He there.

Just trying to get your Python module working with Tapo P100, and I'm getting the following error messge:

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/PyP100/PyP100.py", line 155, in login
    self.token = ast.literal_eval(decryptedResponse)["result"]["token"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./p100.py", line 11, in <module>
    p100.login()
  File "/usr/local/lib/python3.6/dist-packages/PyP100/PyP100.py", line 159, in login
    raise Exception(f"Error Code: {errorCode}, {errorMessage}")
Exception: Error Code: -1501, Invalid Request or Credentials
`

I am pretty sure that all info is currect, as can successfully connect from Tapo app. Tried both versiob from pip and from GitHub with the same result. Don't know where the problem could be as I'm bot a Python coder However I was able to log in to tpcloud via curl and even see that device, althous it says tht it is offline. 

Could you please recommed me what to do?

Thanks in advance.

**Comment by fhnbg** [comment]
have the same issue

**Comment by fhnbg** [comment]
just added a new Tapo plug and everything went fine. Maybe resetting and re-adding your smart plug will fix this issue.

**Comment by technow0rker** [comment]
> 
> 
> just added a new Tapo plug and everything went fine. Maybe resetting and re-adding your smart plug will fix this issue.

Unfortunately, I've done this several times, even tried to change e-mail and password, installing older versions as well as the newest one from Gitub and pip3 -- no changes. OS is Ubuntu 18.0.4, Python 3.6.9. I've read some threads, and the are many people having the same issue. And many for whom it works OK. No one can explain why...

**Comment by technow0rker** [comment]
**UPD:**

Tried to install oldet Python (3.7.0) via pyenv (both local and global) -- no luck. Tried to insyall 6.4 -- no luck eve in virtual Python environment. Problem at login. Did fresh switch factory reset -- no luck. I'm crazy about this. Negotiation seem to work, error arises when login is called.

**Comment by ToXIc-Dev** [comment]
Same issue, changing password and factory resetting didn't work.

**Comment by audoh** [comment]
Yes, there are oddities with the password. So far I've observed:
1. you must reset your plug to update the password https://github.com/fishbigger/TapoP100/issues/3
2. your password cannot contain special characters https://github.com/fishbigger/TapoP100/issues/4

**Comment by mylogon341** [comment]
Just to chirp in on this one - I couldn't get it to work either with -1510 errors on my L510 bulb with a 16 character, strong password. 
I changed the password to an 8 character alphanumeric string + 1 special character and was still getting the same errors. I then removed the device a set it back up and its now working straight away.
Running firmware 1.1.9 (build 20210122)
Worrying, indeed.

**Comment by Floprest64** [comment]
My experience has been the same, reduced password to eight characters and reset plugs, now works

**Comment by DanieleLupo94** [comment]
Hi all.
After months of well working, today my p100 dowsn't works.
If I add a `print(r.json())` after line 189 I can see `{'error_code': 9999}`.
Any solution?

**Comment by fsnuxer** [comment]
Maybe this will help : I sometimes encounter the "KeyError: 'result'"  issue after having pressed the button on the p100 plug to turn it off/on "manually".
( At this point , I can still turn the plug off/on with the official mobile app  )
A workaround that works for me is to unplug/replug  the p100.
( p100 ; hw 1.20.0 ;  fw : 1.4.10 )

**Comment by realzoulou** [comment]
I just updated to Home Assistant Core 2022.4.6 and also updated PyP100 from 0.0.18 to .19 and now run also into an exception 'result' when calling getDeviceName.
I then downgraded only PyP100 to 0.0.18 and all was fine again. 
So, I suspect one of the changes from 0.0.18 to 0.0.19 is not good.

**Comment by goodboyhjlee** [comment]
I had the same issue too  L530E
I solved it by modifying the code.

def login(self):
......
#r = self.session.post(URL, json=SecurePassthroughPayload, headers=headers, timeout=2)
r = self.session.post(URL, json=SecurePassthroughPayload, timeout=2)
.....

**Comment by David-SanchezG** [comment]
@technow0rker how did you change the password to "testing"? From tapo app you need to include some numbers or symbols in the password...
From my side I get the error "Device is offline" even though i can login and see the devices in the network...

**Comment by JeanDaraspe2** [comment]
Dear all,

I get this same error message under Windows 10 Pro with python-3.8.10-amd64 on a P100 plug (firmware 1.4.16 build 20230224) with static IP address (the plug looks ok, I can control it with the Tapo App):

`Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\PyP100\PyP100.py", line 168, in login
    self.token = ast.literal_eval(decryptedResponse)["result"]["token"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "turnoff.py", line 7, in <module>
    p100.login() #Sends credentials to the plug and creates AES Key and IV for further methods
  File "C:\Python38\lib\site-packages\PyP100\PyP100.py", line 172, in login
    raise Exception(f"Error Code: {errorCode}, {errorMessage}")
Exception: Error Code: -1501, Invalid Request or Credentials
`
I tried all the things that are described above without any success (changing password with uppercase, or lowercase or numbers etc , changing account, reset the plug etc....) So I thought it was my P100 plug that maybe have a problem.

I have another P100 plug in another room (same firmware 1.4.16 build 20230224) with static IP address that work perfectly under windows 7 pro with same python-3.8.10-amd64

So I take it to try it with my Windows 10 pro computer using the same script than the windows 7 computer and it doesn't work as well...:(

Both computers are in the same domain. It doesn't work even without firewall.


Some month ago this Windows 10 pro computer works perfectly with the P100 plug.

I reallly don't unsderstand what is the problem here. If someone have an idea?
