### ISSUE TITLE
Stopped Working with Nondescript Error

### ISSUE THREAD

**Issue by markschechter** [fishbigger/TapoP100#108]
Hi! I've really been enjoying this app but unfortunately, it stopped working this week. 

Here's the info: 

My code (with creds redacted): 
```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyP100 import PyP100
>>> 
>>> p100 = PyP100.P100("IP-ADDRESS", "EMAIL", "PASSWORD") #Creates a P100 plug object
>>> 
>>> p100.handshake() #Creates the cookies required for further methods
>>> p100.login() #Sends credentials to the plug and creates AES Key and IV for further methods
>>> 
>>> p100.turnOffWithDelay(200) #Turns the connected plug off after 1 mins
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 351, in turnOffWithDelay
    decryptedResponse = self.tpLinkCipher.decrypt(r.json()["result"]["response"])
KeyError: 'result'
```

I'm using a Tapo smart plug, Firmware: 1.3.6 Build 20210827 Rel. 37578

Any help would greatly be appreciated!

**Comment by markschechter** [comment]
Duplicate issue.
