### ISSUE TITLE
Cannot connect to Tapo P100

### ISSUE THREAD

**Issue by buzzdx** [fishbigger/TapoP100#128]
Hey there, today we got our first Tapo P100 smartplug. Before buying it I looked into controlling it via Python and found this library. I setup the plug via the app and everything works fine, however when trying to use your example code I always get the following error:

File "#PATH#", line 133, in handshake
encryptedKey = r.json()["result"]["key"]
KeyError: 'result'

I printed out the return value (r.json()) of the post method in your code and get this result:

{"error_code":1003}

The App shows the following information about the plug:

Hardware Version 2
Firmware 1.2.1 Build 230804 Rel. 190922

Since I'm using your example code (with my credentials and ip of course) I don't think it's a usage problem. Did the API maybe change and the code needs to be updated? I hope someone can help =)

**Comment by almottier** [comment]
Duplicate of https://github.com/fishbigger/TapoP100/issues/123

**Comment by kebos00** [comment]
For me the handshake problem with the P100 has arisen after the change of firmware from  1.1.0 to 1.2.1 to fix a security bug. This is a shame as I had just started using these functions with a P100 and was amazed that it worked so well until I did a firmware update. I'm now holding off updating my other P100s  which are still OK for now. I do hope someone can find a fix.

**Comment by almottier** [comment]
@kebos00 try this fork: https://github.com/almottier/TapoP100 , it works for P100 version 1.2.1

**Comment by kebos00** [comment]
That's great! I didn't know if I had to uninstall the previous Py100 but as I wasn't sure how to I just installed your fork anyway.
Installing your link failed the first time but worked when I used pip3. Now the P100 is controllable again thanks.
Note to anyone else that using the fork will no longer support firmware before 1.2.1.

**Comment by almottier** [comment]
Hello @kebos00 , I added support for old firmware using a fallback to the old authentification mechanism.

**Comment by kebos00** [comment]
I installed your new code but if I use it on old firmware I get the following  error. It could be me doing something wrong of course but it still works fine on the latest firmware.

    raise Exception(f"Failed to initialize device: {e}")
Exception: Failed to initialize device: Failed to authenticate

**Comment by almottier** [comment]
@kebos00 I think you are still using the old version.
Could you try running this command to re-install the package:
```
pip install --force-reinstall git+https://github.com/almottier/TapoP100.git@main
```

**Comment by kebos00** [comment]
Thanks. I've done that.
I now find that the first time I create the P100 plug object I get an error as below but then it continues and operates the P100 correctly with subsequent P100.turnOn() and P100.turnOff() commands.
I guess that after the initial fail which it reports, it then tries the old authentication which then works.

Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/PyP100/PyP100.py", line 23, in _initialize
    protocol.Initialize()
  File "/home/pi/.local/lib/python3.7/site-packages/PyP100/auth_protocol.py", line 109, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate

**Comment by almottier** [comment]
Yes, the error message is expected as it will first try the new authentication protocol. It could be avoided by using an optional parameter passing the protocol to use.

**Comment by kebos00** [comment]
Thank you very much. Your fix is much appreciated!

**Comment by hams-i** [comment]
https://github.com/almottier/TapoP100 this is working.
Thank you Batuttu.

**Comment by hams-i** [comment]
Hi dude @almottier thank you for new fork, how did you fix it? can you explain?

**Comment by almottier** [comment]
Hello @hams-i , 
It is explained in the forks README. I took the code from another project supporting the new auth and adapted it to be retro-compatible with `TapoP100`.
I may create a new pip package as the maintainer @fishbigger looks no longer active.

**Comment by RFNO** [comment]
Hello, I still have an result error. I'm using handshake and login otherwise I get an errot ('P100' object has no attribute 'token'), but these methods are deprecated, how to replace them ?

**Comment by almottier** [comment]
Hi @RFNO 
Did you try to install the fork like this?
```
pip install --force-reinstall git+https://github.com/almottier/TapoP100.git@main
```
You should not need to call login or handshake. If you still have a problem, please open an Issue [in the fork](https://github.com/almottier/TapoP100/issues) with the error details.

**Comment by RFNO** [comment]
No, so I try ... The install get no error but ... Still 'P100' object has no attribute 'token'

Nevertheless, it works with library tapo (but harder to use)

**Comment by RFNO** [comment]
I tried again but the command doesn't work with windows... 

ERROR: Error [WinError 2] Le fichier spécifié est introuvable while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

It works with git installed, and now your library works too. Thank you for your work.

**Comment by baishi** [comment]
I confirm @almottier 's fix works for me. Thanks for the contribution @almottier !

**Comment by Eserim** [comment]
Many thanks for this - I've had to resort to this as the official control app wouldn't allow me to create an automation with a quick on then off in order to control a fish tank light that uses that to toggle the mode.

**Comment by mrx23dot** [comment]
So I was stupid enough to update the firmware on Tapo L510 light bulb to v1.3.1.

This branch works for me:
https://github.com/almottier/TapoP100

I use it as a sunrise simulator before the alarm clock goes off, it became essential in winter.

**Comment by AdamBrez** [comment]
@almottier Thank you for the fork. You are a lifesaver

**Comment by p0hamala** [comment]
Hi All,
I just purchased a set of 4 Tapo P110 plugs. Those contain firmware 1.3.0 from factory which works flawlessly with latest pyp100. However, there is an firmware update v.1.4.6 for these plugs. FW update is automatically ON on tapo app and after that update pyp100 lib is not able to connect to these devices any more. This needs some investigation and work. Currently I have both these versions available so I can do some troubleshooting if I get hints what to look for.

**Comment by p0hamala** [comment]
Answering to my comment above and info for all: when tapo_p110 firmware is upgraded to v1.4.6 (1.4.0 also?), I had to remove the devices from tapo mobile app and deactivate 3rd party compatibility - and then add the same devices back to tapo app and re-activate 3rd party integration. With these steps access to the p110 devices was ok again. BTW this problem and solution  was suggested by many in tp-link forums. Case closed from my behalf.
