### ISSUE TITLE
P105?

### ISSUE THREAD

**Issue by fmarzocca** [fishbigger/TapoP100#138]
I can't get this working on a P105:

```Traceback (most recent call last):
  File "/home/boss/.node-red/assets/./TapoP100.py", line 33, in <module>
    p100.handshake()
  File "/usr/local/lib/python3.11/dist-packages/PyP100/PyP100.py", line 129, in handshake
    encryptedKey = r.json()["result"]["key"]
                   ~~~~~~~~^^^^^^^^^^
KeyError: 'result'
```

**Comment by KaiHomeier** [comment]
This error popped up from nowhere on my bulb as well.
I migrated my project to https://github.com/petretiandrea/plugp100 which is working fine now.
