### ISSUE TITLE
Error code:-1003 when using getEnergyUsage in P110

### ISSUE THREAD

**Issue by yslim2002** [fishbigger/TapoP100#139]
Error: {'error_code': -1003}
Traceback (most recent call last):
File "d:\Python\Training\Practice\tapo110.py", line 8, in
p110.getEnergyUsage()
File "D:\Anaconda\Lib\site-packages\PyP100\PyP100.py", line 109, in getEnergyUsage
return self.request("get_energy_usage")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Anaconda\Lib\site-packages\PyP100\PyP100.py", line 47, in request
return self.protocol._request(method, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Anaconda\Lib\site-packages\PyP100\auth_protocol.py", line 65, in _request
raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: -1003

**Comment by bertkdowns** [comment]
see issue #128 , #136, #123

```
pip remove pyp100
pip install git+https://github.com/almottier/TapoP100.git@main
```
