### ISSUE TITLE
p100.handshake() not working

### ISSUE THREAD

**Issue by saepien** [fishbigger/TapoP100#143]
`
>>> tape = PyP100.P100("192.168.1.140", "test@gmail.com", "test")
>>> tape.handshake()
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    tape.handshake()
    ~~~~~~~~~~~~~~^^
  File "/Users/storm/dev/sandbox/tapo/env/lib/python3.13/site-packages/PyP100/PyP100.py", line 129, in handshake
    encryptedKey = r.json()["result"]["key"]
                   ~~~~~~~~^^^^^^^^^^
KeyError: 'result'
`

**Comment by SolarCTP** [comment]
having the same issue. the plug replies to the handshake with `{'error_code': 1003}`. it may have something to do with the new firmware. I'm running version 1.5.5.

**Comment by finlaybob** [comment]
Having the same problem with `{"error_code":1003}` in the response.

P100 firmware version is `1.5.5 Build 20230927 Rel.40646`
