### ISSUE TITLE
333 Error Code: -1501, Invalid Request or Credentials

### ISSUE THREAD

**Issue by 49jpg** [fishbigger/TapoP100#27]
I have this problem [Tapo Smart Platform] 333 Error Code: -1501, Invalid Request or Credentials
Any help?

**Comment by jimbob0119** [comment]
me too

**Comment by a0s** [comment]
+1 it just doesn't work

```
Traceback (most recent call last):
  File "/Users/a0s/3dprinting/tapo-test/.direnv/python-3.9.6/lib/python3.9/site-packages/PyP100/PyP100.py", line 159, in login
    self.token = ast.literal_eval(decryptedResponse)["result"]["token"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a0s/3dprinting/tapo-test/main.py", line 6, in <module>
    print(p100.login())
  File "/Users/a0s/3dprinting/tapo-test/.direnv/python-3.9.6/lib/python3.9/site-packages/PyP100/PyP100.py", line 163, in login
    raise Exception(f"Error Code: {errorCode}, {errorMessage}")
Exception: Error Code: -1501, Invalid Request or Credentials
```
