### ISSUE TITLE
L900 not logging in anymore

### ISSUE THREAD

**Issue by jimbob0119** [fishbigger/TapoP100#37]
I was trying to use this library with my l900 led strip like my bulb, at first it worked, then it started to work with one function and spit out a handshake error and now it won't even login

```
james@james-desktop:~/Documents/TAPO-And-Govee-Controller-py$ python3 main.py
Traceback (most recent call last):
  File "/home/james/Documents/TAPO-And-Govee-Controller-py/main.py", line 25, in <module>
    lightStrip.login()
  File "/home/james/.local/lib/python3.9/site-packages/PyP100/PyP100.py", line 156, in login
    decryptedResponse = self.tpLinkCipher.decrypt(r.json()["result"]["response"])
  File "/home/james/.local/lib/python3.9/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by fishbigger** [comment]
Hi, 
Sorry this has taken so long... Is the ip address of the l900 still the sane?
