### ISSUE TITLE
Unable to login to the 530B Bulb due to JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by amanbatra1996** [fishbigger/TapoP100#54]
This is the error I am getting on trying to login:
raise JSONDecodeError("Expecting value", s, err.value) from None

I am trying out with the 530B bulb and the following code:
```
from PyP100 import PyL530

l530 = PyL530.L530("192.168.29.207", "abatra19620@gmail.com", "srapsra1") #Creating a L530 bulb object

l530.handshake() #Creates the cookies required for further methods
l530.login() #Sends credentials to the plug and creates AES Key and IV for further methods
```
handshake happens without any errors, the error pops up during login 

When I was trying to go through other issues, it was suggested that it might be an authentication related issue, but changing passwords did not help either. I am also making sure its an 8 digit password.

Please let me know if any other information is required, I request you to help me solve this, Thanks!

**Comment by vijayrraut** [comment]
I am also facing same error:

>>> l530.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/PyP100/PyP100.py", line 156, in login
    decryptedResponse = self.tpLinkCipher.decrypt(r.json()["result"]["response"])
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by fishbigger** [comment]
Hi,
I can't immediately see what the problem is here. Have you ever had the code working on an older version or is this your first time trying it? I'm trying to work out if I've screwed up somewhere while refactoring some of the code.
Thanks.

**Comment by amanbatra1996** [comment]
Hi, 
Sorry for the delayed response. This was the first time I was trying to login using the latest code of the time. I am not sure that if code is itself buggy. I was wondering if the router used could have caused some restriction in communication. I will try to test it again sometime using a mobile hotspot based network to confirm. I have actually moved to university so bit difficult to follow up, nevertheless I will update the thread once I experiment with another network. Thanks for your response!

**Comment by fishbigger** [comment]
Hi,
Thanks for your response! Please do let me know if you have any success with the hotspot. I haven't encountered the router as an issue before but if it is that could explain some of the other issues.
Thanks.

**Comment by Lemos97** [comment]
Facing the same issue as described. 
The `response.text` from the post of the login method is: 
`<html><body><center>200 OK</center></body></html>` 
Which is why it is raising the following Exception, the same as the original issue. 
```
File "E:\Dev\light-bulb-TPLL530\room.py", line 67, in main
    p100.login() #Sends credentials to the plug and creates AES Key and IV for further methods
  File "E:\Dev\light-bulb-TPLL530\devices\PyP100.py", line 162, in login
    decryptedResponse = r.json()["result"]["response"]
  File "C:\Python39\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Noah-1337** [comment]
Currently getting the same error but i was unable to find a solution, what can i do?
![grafik](https://user-images.githubusercontent.com/97415279/169671593-d7c32760-577a-4ffb-ba10-23013d298111.png)

**Comment by alenoi** [comment]
![image](https://user-images.githubusercontent.com/67100159/188732858-b33fb26b-d50c-4861-9ce1-bf145a4addea.png)
So I checked this part in the 'login' and it seems that the reqest does not get a json response anymore in case of L530* bulbs

**Comment by alenoi** [comment]
![image](https://user-images.githubusercontent.com/67100159/188733539-d06034d9-8f6d-41cf-8dd2-61b48ed08b11.png)
So it seems like there is no json in the bulb's reponses anymore only a HTTP200 (the plugs response still contains the json)
